"""SKIDL code emitter — generates Python build_*.py from circuit data."""

from __future__ import annotations
from typing import Optional


class SkidlEmitter:
    """Generates SKIDL Python code from extracted circuit data."""
    
    def emit(self, board_name: str, components: list[dict],
             nets: dict, power_nets: set, level: str = "L1") -> str:
        """Generate a complete build_*.py script.
        
        Args:
            board_name: Name for the board (e.g. "adsr")
            components: List of component dicts with ref, lib_id, value, footprint, mapped
            nets: Dict of net_name → [{ref, pin_number, pin_name}, ...]
            power_nets: Set of power net names (GND, +3V3, etc.)
            level: "L1" (pin-level) or "L2" (component-level)
        
        Returns:
            Complete Python script as a string.
        """
        lines = []
        
        # Header
        lines.append(f'#!/usr/bin/env python3')
        lines.append(f'"""')
        lines.append(f'build_{board_name}.py — Auto-generated from {board_name}.kicad_sch')
        lines.append(f'Generated by kicad-agent circuit_ir converter (level={level}).')
        lines.append(f'"""')
        lines.append(f'from __future__ import annotations')
        lines.append(f'import os, sys')
        lines.append(f'')
        lines.append(f'os.environ["KICAD_SYMBOL_DIR"] = "/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols"')
        lines.append(f'for v in ("KICAD5", "KICAD6", "KICAD7", "KICAD8", "KICAD9"):')
        lines.append(f'    os.environ[f"{{v}}_SYMBOL_DIR"] = os.environ["KICAD_SYMBOL_DIR"]')
        lines.append(f'')
        lines.append(f'sys.path.insert(0, os.path.dirname(__file__))')
        lines.append(f'')
        lines.append(f'from parts import *')
        lines.append(f'from skidl import Net, Circuit')
        lines.append(f'')
        lines.append(f'')
        lines.append(f'def build_board() -> Circuit:')
        lines.append(f'    ckt = Circuit()')
        lines.append(f'')
        lines.append(f'    with ckt:')
        
        # Power nets
        if power_nets:
            lines.append(f'        # ===== POWER NETS =====')
            for pn in sorted(power_nets):
                if pn and pn != "PWR_FLAG":
                    lines.append(f'        {self._net_var(pn)} = Net("{pn}")')
            lines.append(f'')
        
        # Components
        lines.append(f'        # ===== COMPONENTS ({len(components)} total) =====')
        for comp in components:
            lines.append(f'        {self._emit_component(comp)}')
        lines.append(f'')
        
        # Nets (connectivity)
        lines.append(f'        # ===== NET CONNECTIVITY ({len(nets)} nets) =====')
        for net_name, pins in sorted(nets.items()):
            if not pins or net_name in power_nets:
                continue
            net_var = self._net_var(net_name) if net_name != net_name.upper() else net_name.lower()
            lines.append(f'        {net_var} = Net("{net_name}")')
            for pin in pins:
                ref = pin.get("ref", "")
                pin_num = pin.get("pin_number", "")
                if ref and pin_num:
                    lines.append(f'        {net_var} += {ref}["{pin_num}"]')
            lines.append(f'')
        
        # Footer
        lines.append(f'    return ckt')
        lines.append(f'')
        lines.append(f'')
        lines.append(f'if __name__ == "__main__":')
        lines.append(f'    print("Building {board_name}...")')
        lines.append(f'    ckt = build_board()')
        lines.append(f'    print(f"\\n{{len(ckt.parts)}} parts, {{len(ckt.nets)}} nets")')
        lines.append(f'    print("\\nRunning ERC...")')
        lines.append(f'    ckt.ERC()')
        lines.append(f'    ckt.generate_netlist(file_="{board_name}.net")')
        lines.append(f'    print(f"✓ Netlist → {board_name}.net")')
        lines.append(f'')
        
        return "\n".join(lines)
    
    def _emit_component(self, comp: dict) -> str:
        """Emit a single component instantiation."""
        ref = comp["ref"]
        value = comp["value"]
        footprint = comp["footprint"]
        mapped = comp["mapped"]
        
        if mapped.strategy == "wrapper":
            if mapped.wrapper_name and mapped.wrapper_name != "None":
                return f'{ref} = {mapped.wrapper_name}(ckt, "{ref}")  # {value}'
            else:
                # Wrapper is None — fall through to connector mode
                pass
        elif mapped.strategy == "generic":
            fp_str = f', footprint="{footprint}"' if footprint else ''
            val_str = f'value="{value}"' if value else ''
            return f'{ref} = Part("Device", "{mapped.lib_id.split(":")[-1]}", {val_str}{fp_str})  # {ref}'
        elif mapped.strategy == "connector":
            return f'{ref} = Part("Connector_Generic", "Conn_01x{mapped.pin_count:02d}", value="{value}", footprint="{footprint}")  # generated wrapper'
        return f'# TODO: {ref} = unknown part ({mapped.lib_id})'
    
    def _net_var(self, name: str) -> str:
        """Convert a net name to a valid Python variable name."""
        var = name.replace("+", "p").replace("-", "n").replace(" ", "_")
        var = var.replace(".", "_").replace("/", "_").replace("(", "").replace(")", "")
        var = ''.join(c if c.isalnum() or c == '_' else '_' for c in var)
        if var and var[0].isdigit():
            var = "n_" + var
        return var.lower()
