"""Phase 156 Wave 2: L1/L2 SKIDL code emission.

Emits executable build_*.py SKIDL programs from a CircuitIR. Two modes:
  - L1 (pin-level, exact): one += statement per pin connection. Round-trip faithful.
  - L2 (component-level, training): compact, grouped, LLM training-friendly.

Both consume the same CircuitIR — they differ only in emission format.
SchGen proved L1 achieves 82% valid circuit generation vs 32% for raw KiCad.
"""
from __future__ import annotations

from pathlib import Path

from kicad_agent.circuit_ir.types import CircuitIR, NetDescriptor, PartDescriptor


def emit_build_py(
    circuit_ir: CircuitIR,
    mode: str = "L1",
    out_path: Path | None = None,
) -> Path:
    """Emit a standalone build_*.py SKIDL program.

    Args:
        circuit_ir: The circuit intermediate representation.
        mode: "L1" (pin-level exact) or "L2" (component-level training).
        out_path: Output file path. If None, returns code as string.

    Returns:
        The path to the written file (or the code string if out_path is None).
    """
    if mode == "L1":
        code = _emit_l1(circuit_ir)
    elif mode == "L2":
        code = _emit_l2(circuit_ir)
    else:
        raise ValueError(f"Unknown emission mode: {mode}")

    if out_path is not None:
        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(code, encoding="utf-8")
        return out_path
    return code  # type: ignore[return-value]


def _emit_l1(circuit_ir: CircuitIR) -> str:
    """Emit L1 (pin-level, exact) SKIDL code.

    Every pin-to-net assignment is explicit, matching source connectivity 1:1.
    This is the Code-L1 representation SchGen proved achieves 82% validity.
    """
    lines: list[str] = []
    stem = Path(circuit_ir.source_file).stem

    # Header
    lines.append("#!/usr/bin/env python3")
    lines.append(f'"""build_{stem}.py — Auto-generated from {stem}.kicad_sch')
    lines.append(f"Generated by kicad-agent circuit_ir (L1 pin-level).")
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("import os, sys")
    lines.append("")
    lines.append('os.environ["KICAD_SYMBOL_DIR"] = "/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols"')
    lines.append('for v in ("KICAD5", "KICAD6", "KICAD7", "KICAD8", "KICAD9"):')
    lines.append('    os.environ[f"{v}_SYMBOL_DIR"] = os.environ["KICAD_SYMBOL_DIR"]')
    lines.append("")
    lines.append("from skidl import Part, Net, NC, Circuit")
    lines.append("")
    lines.append("")
    lines.append("def build_board() -> Circuit:")
    lines.append("    ckt = Circuit()")
    lines.append("")
    lines.append("    with ckt:")
    lines.append("")

    # Power nets first
    power_nets = [n for n in circuit_ir.nets if n.is_power]
    signal_nets = [n for n in circuit_ir.nets if not n.is_power]

    if power_nets:
        lines.append("        # ===== POWER NETS =====")
        for pn in power_nets:
            var = _net_var(pn.name)
            lines.append(f'        {var} = Net("{pn.name}")')
        lines.append("")

    # Components
    lines.append(f"        # ===== COMPONENTS ({len(circuit_ir.parts)} total) =====")
    for pd in circuit_ir.parts:
        lines.append(f"        {_emit_part_l1(pd)}")
    lines.append("")

    # Signal nets (L1: pin-level wiring)
    lines.append(f"        # ===== NET CONNECTIVITY ({len(signal_nets)} signal nets) =====")
    for net in signal_nets:
        var = _net_var(net.name)
        lines.append(f'        {var} = Net("{net.name}")')
        for pin in net.pins:
            pin_ref = f'{pin.reference}["{pin.pin_number}"]'
            lines.append(f"        {var} += {pin_ref}")
        lines.append("")

    # Power net connections
    if power_nets:
        lines.append("        # ===== POWER CONNECTIONS =====")
        for net in power_nets:
            var = _net_var(net.name)
            for pin in net.pins:
                pin_ref = f'{pin.reference}["{pin.pin_number}"]'
                lines.append(f"        {var} += {pin_ref}")
        lines.append("")

    # Footer
    lines.append("    return ckt")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append(f'    print("Building {stem}...")')
    lines.append("    ckt = build_board()")
    lines.append('    print(f"\\n{len(ckt.parts)} parts, {len(ckt.nets)} nets")')
    lines.append('    print("\\nRunning ERC...")')
    lines.append("    nerrors, nwarnings = ckt.ERC()")
    lines.append(f'    ckt.generate_netlist(file_="{stem}.net")')
    lines.append(f'    print(f"Netlist → {stem}.net")')

    return "\n".join(lines) + "\n"


def _emit_l2(circuit_ir: CircuitIR) -> str:
    """Emit L2 (component-level, training-friendly) SKIDL code.

    Compact, grouped by component with net summary dicts. Fewer statements,
    human-readable, optimized for LLM training-token efficiency.
    """
    lines: list[str] = []
    stem = Path(circuit_ir.source_file).stem

    # Header
    lines.append("#!/usr/bin/env python3")
    lines.append(f'"""build_{stem}.py — L2 component-level (training data form)."""')
    lines.append("from __future__ import annotations")
    lines.append("import os")
    lines.append('os.environ["KICAD_SYMBOL_DIR"] = "/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols"')
    lines.append("from skidl import Part, Net, Circuit")
    lines.append("")
    lines.append("")

    # Build net summary per component
    comp_nets: dict[str, dict[str, str]] = {}
    for net in circuit_ir.nets:
        for pin in net.pins:
            comp_nets.setdefault(pin.reference, {})[pin.pin_number] = net.name

    lines.append("def build_board() -> Circuit:")
    lines.append("    ckt = Circuit()")
    lines.append("    with ckt:")
    lines.append("")

    # Components with net summaries
    for pd in circuit_ir.parts:
        lib, name = pd.lib_id.split(":", 1) if ":" in pd.lib_id else ("Device", pd.lib_id)
        fp_str = f', footprint="{pd.footprint}"' if pd.footprint else ""
        val_str = f'value="{pd.value}"' if pd.value else ""
        lines.append(f'        {pd.reference} = Part("{lib}", "{name}", {val_str}{fp_str})')
        nets_dict = comp_nets.get(pd.reference, {})
        if nets_dict:
            summary = ", ".join(f'"{k}": "{v}"' for k, v in sorted(nets_dict.items()))
            lines.append(f"        # nets: {{{summary}}}")
    lines.append("")

    # Net declarations (L2: just names, connections via the summary)
    lines.append("        # Nets (see per-component summaries above)")
    all_net_names = sorted({n.name for n in circuit_ir.nets})
    for name in all_net_names:
        lines.append(f'        {_net_var(name)} = Net("{name}")')
    lines.append("")

    lines.append("    return ckt")
    lines.append("")

    return "\n".join(lines) + "\n"


def _emit_part_l1(pd: PartDescriptor) -> str:
    """Emit a single Part instantiation for L1 mode."""
    lib, name = pd.lib_id.split(":", 1) if ":" in pd.lib_id else ("Device", pd.lib_id)
    kwargs: list[str] = []
    if pd.value:
        kwargs.append(f'value="{pd.value}"')
    if pd.footprint:
        kwargs.append(f'footprint="{pd.footprint}"')
    kwargs_str = ", ".join(kwargs)
    return f'{pd.reference} = Part("{lib}", "{name}", {kwargs_str})  # {pd.reference}'


def _net_var(name: str) -> str:
    """Convert a net name to a valid Python variable name."""
    var = name.replace("+", "p").replace("-", "n").replace(" ", "_")
    var = var.replace(".", "_").replace("/", "_").replace("(", "").replace(")", "")
    var = "".join(c if c.isalnum() or c == "_" else "_" for c in var)
    if var and var[0].isdigit():
        var = "n_" + var
    return var.lower()
