"""PcbRawWriter -- centralized raw S-expression manipulation for PCB files.

All methods return modified content strings (Council C-01). The caller
(executor or handler) is responsible for writing to disk via atomic
temp+rename and cache invalidation.

Consolidates raw-write sites (Council C-02):
- insert_track_segments (was in ir/pcb_ir.py)
- assign_net_class (was in ops/pcb_ops.py)
- update_footprint (was in ir/pcb_ir.py)
- insert_zone (new for #38)
- modify_footprint_position (new for #39)
- build_segment_sexp / build_arc_sexp / build_via_sexp (new for Phase 101-01)

Usage:
    from kicad_agent.ops.pcb_raw_writer import PcbRawWriter

    content = PcbRawWriter.insert_segments(raw, sexpr_blocks)
    content = PcbRawWriter.assign_net_class(raw, net_name, class_name)
"""

import re
import uuid
from pathlib import Path
from typing import Any, Optional


class PcbRawWriter:
    """Stateless utility class for raw PCB S-expression manipulation.

    Every method takes raw S-expression content and returns new content.
    No method writes to disk or accesses the filesystem.
    """

    # ------------------------------------------------------------------
    # Track segments (#37)
    # ------------------------------------------------------------------

    @staticmethod
    def insert_segments(content: str, sexpr_blocks: str) -> str:
        """Insert track segment S-expressions before the closing paren.

        Args:
            content: Raw .kicad_pcb S-expression text.
            sexpr_blocks: One or more (segment ...) S-expression strings.

        Returns:
            Modified content with segments inserted.
        """
        last_close = content.rfind(")")
        if last_close == -1:
            return content
        insertion = "\n" + sexpr_blocks + "\n"
        return content[:last_close] + insertion + content[last_close:]

    # ------------------------------------------------------------------
    # Copper zone (#38, #65)
    # ------------------------------------------------------------------

    @staticmethod
    def insert_zone(
        content: str,
        zone_sexp: str,
    ) -> str:
        """Insert a copper zone S-expression before the closing paren.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_sexp: Complete (zone ...) S-expression block.

        Returns:
            Modified content with zone inserted.
        """
        last_close = content.rfind(")")
        if last_close == -1:
            return content
        insertion = "\n" + zone_sexp + "\n"
        return content[:last_close] + insertion + content[last_close:]

    @staticmethod
    def build_zone_sexp(
        net_number: int,
        net_name: str,
        layer: str,
        polygon: list[tuple[float, float]],
        clearance: float = 0.5,
        min_thickness: float = 0.25,
        priority: int = 0,
        uuid: str = "00000000-0000-0000-0000-000000000000",
    ) -> str:
        """Build a KiCad copper zone S-expression.

        Generates zones matching the board's file format:
        - Older KiCad (version 20250125): (net N "name") format
        - Newer KiCad (version 20260206): (net "name") format

        KiCad fills (filled_polygon, filled_areas) are auto-generated by
        the zone filler on save -- never included in hand-written zones.

        Fixes #65: proper KiCad 10 S-expression format with quoted UUIDs,
        correct net field, no stub filled_polygon, no invalid fields.

        Args:
            net_number: Net number for the zone.
            net_name: Net name (e.g. "GND").
            layer: Copper layer (e.g. "F.Cu", "B.Cu").
            polygon: Outline polygon as [(x, y), ...].
            clearance: Zone clearance in mm.
            min_thickness: Minimum fill width in mm.
            priority: Zone priority (higher = filled first).
            uuid: Zone UUID (quoted in output per KiCad format).

        Returns:
            Complete (zone ...) S-expression string.
        """
        # Build polygon points as single-line (xy ...) entries
        xy_entries = " ".join(
            f"(xy {x:g} {y:g})" for x, y in polygon
        )

        # KiCad 10 zone net format (Bead analog-ecosystem-19 fix):
        # Real KiCad 10 boards (version 20260206) use string-only (net "NAME").
        # The legacy (net N)(net_name "NAME") form was WRONG — it caused
        # kicad-cli 'Failed to load board' on analog-board during Phase 129.
        # Verified against working digital-board which uses (net "GND").
        # For empty net_name (keepouts), emit (net "") — KiCad accepts this.
        net_line = f'(net "{net_name}")'

        # UUID quoted per KiCad S-expression format
        uuid_line = f'(uuid "{uuid}")'

        # Optional priority line -- only emit when nonzero to match the
        # KiCad writer's behavior (priority 0 is the default and omitted).
        priority_line = f'    (priority {priority})\n' if priority > 0 else ''

        parts = [
            '  (zone',
            f'    {net_line}',
            f'    (layer "{layer}")',
            f'    {uuid_line}',
            '    (hatch edge 0.5)',
            priority_line +
            '    (connect_pads',
            f'      (clearance {clearance:g})',
            '    )',
            f'    (min_thickness {min_thickness:g})',
            '    (filled_areas_thickness no)',
            '    (fill',
            f'      (thermal_gap {clearance:g})',
            f'      (thermal_bridge_width {clearance:g})',
            '    )',
            '    (polygon',
            '      (pts',
            f'        {xy_entries}',
            '      )',
            '    )',
            '  )',
        ]

        return "\n".join(parts) + "\n"

    # ------------------------------------------------------------------
    # Zone lifecycle (find, modify, remove) -- Plan 79-03
    # ------------------------------------------------------------------

    @staticmethod
    def find_zone_block(
        content: str, zone_uuid: str,
    ) -> tuple[Optional[int], Optional[int]]:
        """Find a zone block by UUID in raw PCB content.

        Scans for ``(zone`` blocks and checks if the block contains the
        target UUID. Uses ``_find_matching_close()`` for correct handling
        of nested parens (T-79-01).

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID string to search for.

        Returns:
            (start, end) byte offsets, or (None, None) if not found.
        """
        uuid_pat = re.compile(
            r'\(uuid\s+"' + re.escape(zone_uuid) + r'"'
        )
        for match in re.finditer(r"^\s*\(zone\b", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue
            block = content[start : end + 1]
            if uuid_pat.search(block):
                return start, end + 1
        return None, None

    @staticmethod
    def find_zone_block_by_index(
        content: str, index: int,
    ) -> tuple[Optional[int], Optional[int]]:
        """Find the Nth zone block (0-indexed) in raw PCB content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            index: 0-based zone index.

        Returns:
            (start, end) byte offsets, or (None, None) if not found.
        """
        count = 0
        for match in re.finditer(r"^\s*\(zone\b", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue
            if count == index:
                return start, end + 1
            count += 1
        return None, None

    @staticmethod
    def modify_zone_field(
        content: str, zone_uuid: str, field: str, value: Any,
    ) -> str:
        """Modify a single field within a zone block.

        Supported fields: ``net_name``, ``layer``, ``clearance``,
        ``priority``, ``min_width``.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID of the zone to modify.
            field: Field name to change.
            value: New value for the field.

        Returns:
            Modified content, or original if zone not found.
        """
        start, end = PcbRawWriter.find_zone_block(content, zone_uuid)
        if start is None or end is None:
            return content

        block = content[start:end]

        if field == "net_name":
            # D-13 + H-05: Extract existing net number from content before substitution.
            # Do NOT add ir parameter to @staticmethod (API contract).
            existing_net_match = re.search(r'\(net\s+(\d+)\s+"[^"]*"\)', block)
            existing_net_id = int(existing_net_match.group(1)) if existing_net_match else 0
            block = re.sub(
                r'\(net\s+\d+\s+"[^"]*"\)',
                f'(net {existing_net_id} "{value}")',
                block,
                count=1,
            )
        elif field == "layer":
            block = re.sub(
                r'\(layer\s+"[^"]*"\)',
                f'(layer "{value}")',
                block,
                count=1,
            )
        elif field == "clearance":
            # Replace clearance inside (connect_pads ... (clearance X))
            block = re.sub(
                r'\(clearance\s+[-\d.]+\)',
                f'(clearance {value:g})',
                block,
                count=1,
            )
        elif field == "priority":
            if "(priority " in block:
                block = re.sub(
                    r'\(priority\s+\d+\)',
                    f'(priority {value})',
                    block,
                    count=1,
                )
            else:
                # Insert priority after min_thickness line
                block = re.sub(
                    r'(\(min_thickness\s+[-\d.]+\))',
                    f'\\1\n    (priority {value})',
                    block,
                    count=1,
                )
        elif field == "min_width":
            block = re.sub(
                r'\(min_thickness\s+[-\d.]+\)',
                f'(min_thickness {value:g})',
                block,
                count=1,
            )

        return content[:start] + block + content[end:]

    @staticmethod
    def modify_zone_polygon(
        content: str,
        zone_uuid: str,
        polygon: list[tuple[float, float]],
    ) -> str:
        """Replace the polygon outline of a zone block.

        Finds the ``(polygon (pts ...))`` sub-block within the zone and
        replaces the xy entries with new polygon points.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID of the zone to modify.
            polygon: New polygon outline as [(x, y), ...].

        Returns:
            Modified content, or original if zone not found.
        """
        start, end = PcbRawWriter.find_zone_block(content, zone_uuid)
        if start is None or end is None:
            return content

        block = content[start:end]

        xy_entries = " ".join(
            f"(xy {x:g} {y:g})" for x, y in polygon
        )
        new_pts_block = f"        {xy_entries}"

        # Replace content between (pts and closing ))
        block = re.sub(
            r'(\(pts\s*\n).*?(\n\s*\))',
            lambda m: f'(pts\n{new_pts_block}\n      )',
            block,
            count=1,
            flags=re.DOTALL,
        )

        return content[:start] + block + content[end:]

    @staticmethod
    def remove_zone_block(content: str, zone_uuid: str) -> str:
        """Remove a zone block entirely from raw PCB content.

        Removes the zone block including its surrounding whitespace.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID of the zone to remove.

        Returns:
            Modified content with zone removed, or original if not found.
        """
        start, end = PcbRawWriter.find_zone_block(content, zone_uuid)
        if start is None or end is None:
            return content

        # Include leading newline if present
        trim_start = start
        if trim_start > 0 and content[trim_start - 1] == "\n":
            trim_start -= 1

        return content[:trim_start] + content[end:]

    # ------------------------------------------------------------------
    # Net class (#40 migration)
    # ------------------------------------------------------------------

    @staticmethod
    def assign_net_class(
        content: str,
        net_name: str,
        net_class_name: str,
    ) -> str:
        """Add or update a net class assignment in raw PCB content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            net_name: Name of the net to assign.
            net_class_name: Name of the net class.

        Returns:
            Modified content string.
        """
        # Remove this net from any existing net_class blocks
        add_net_pattern = re.compile(
            r'\(add_net "' + re.escape(net_name) + r'"\)\s*\n?'
        )
        content = add_net_pattern.sub("", content)

        # Find or create the target net_class block
        class_pattern = re.compile(
            r'\(net_class "' + re.escape(net_class_name) + r'"'
        )
        match = class_pattern.search(content)
        if match:
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start)
            if end is not None:
                insertion = f'\n      (add_net "{net_name}")'
                content = content[:end] + insertion + content[end:]
        else:
            # Create new net_class block before the first (net ... ) line
            new_class = (
                f'  (net_class "{net_class_name}" ""\n'
                f'    (add_net "{net_name}")\n'
                f'  )\n'
            )
            first_net = re.search(r'\n  \(net \d+ ', content)
            if first_net:
                content = (
                    content[:first_net.start()]
                    + "\n"
                    + new_class
                    + content[first_net.start() :]
                )
            else:
                content = content.rstrip() + "\n" + new_class + ")\n"

        return content

    # ------------------------------------------------------------------
    # Footprint position (#39)
    # ------------------------------------------------------------------

    @staticmethod
    def modify_footprint_position(
        content: str,
        reference: str,
        x: float,
        y: float,
        angle: float = 0.0,
    ) -> str:
        """Move a footprint to a new position in raw PCB content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            reference: Reference designator (e.g. "R1").
            x: New X position in mm.
            y: New Y position in mm.
            angle: New rotation angle in degrees.

        Returns:
            Modified content string, or original if footprint not found.
        """
        start, end = PcbRawWriter._find_footprint_block(content, reference)
        if start is None or end is None:
            return content

        block = content[start:end]

        # Replace (at X Y angle) in the footprint block
        at_pattern = re.compile(
            r'\(at\s+[-\d.]+\s+[-\d.]+(?:\s+[-\d.]+)?\s*\)'
        )
        new_at = f"(at {x:.6f} {y:.6f} {angle:.6f})"
        new_block = at_pattern.sub(new_at, block, count=1)

        return content[:start] + new_block + content[end:]

    # ------------------------------------------------------------------
    # Track / arc / via builders (Phase 101-01)
    # ------------------------------------------------------------------

    @staticmethod
    def build_segment_sexp(
        start: tuple[float, float],
        end: tuple[float, float],
        width: float,
        layer: str,
        net_name: str,
        uuid_str: Optional[str] = None,
    ) -> str:
        """Build a KiCad 10 ``(segment ...)`` S-expression for a straight track.

        Uses the KiCad 10 string-only net reference ``(net "NAME")`` --
        NOT the legacy ``(net N "NAME")`` form (H3: segment-net-format).

        Args:
            start: (x, y) start coordinates in mm.
            end: (x, y) end coordinates in mm.
            width: Trace width in mm.
            layer: Copper layer name (e.g. "F.Cu").
            net_name: Net name (e.g. "GND").
            uuid_str: Optional UUID string. If None, a new uuid4 is generated.

        Returns:
            Complete ``(segment ...)`` S-expression block (indented, trailing newline).
        """
        if uuid_str is None:
            uuid_str = str(uuid.uuid4())

        sx, sy = start
        ex, ey = end
        parts = [
            "  (segment",
            f"    (start {sx:g} {sy:g})",
            f"    (end {ex:g} {ey:g})",
            f"    (width {width:g})",
            f'    (layer "{layer}")',
            f'    (net "{net_name}")',
            f'    (uuid "{uuid_str}")',
            "  )",
        ]
        return "\n".join(parts) + "\n"

    @staticmethod
    def build_arc_sexp(
        start: tuple[float, float],
        mid: tuple[float, float],
        end: tuple[float, float],
        width: float,
        layer: str,
        net_name: str,
        uuid_str: Optional[str] = None,
    ) -> str:
        """Build a KiCad 10 ``(arc ...)`` S-expression for a curved track.

        Uses the KiCad 10 string-only net reference ``(net "NAME")``.

        Args:
            start: (x, y) arc start coordinates in mm.
            mid: (x, y) arc midpoint coordinates in mm.
            end: (x, y) arc end coordinates in mm.
            width: Trace width in mm.
            layer: Copper layer name (e.g. "F.Cu").
            net_name: Net name (e.g. "GND").
            uuid_str: Optional UUID string. If None, a new uuid4 is generated.

        Returns:
            Complete ``(arc ...)`` S-expression block (indented, trailing newline).
        """
        if uuid_str is None:
            uuid_str = str(uuid.uuid4())

        sx, sy = start
        mx, my = mid
        ex, ey = end
        parts = [
            "  (arc",
            f"    (start {sx:g} {sy:g})",
            f"    (mid {mx:g} {my:g})",
            f"    (end {ex:g} {ey:g})",
            f"    (width {width:g})",
            f'    (layer "{layer}")',
            f'    (net "{net_name}")',
            f'    (uuid "{uuid_str}")',
            "  )",
        ]
        return "\n".join(parts) + "\n"

    @staticmethod
    def build_via_sexp(
        at: tuple[float, float],
        size: float,
        drill: float,
        layers: list[str],
        net_name: str,
        uuid_str: Optional[str] = None,
    ) -> str:
        """Build a KiCad 10 ``(via ...)`` S-expression.

        Uses the KiCad 10 string-only net reference ``(net "NAME")``.

        Args:
            at: (x, y) via center coordinates in mm.
            size: Via pad diameter in mm.
            drill: Via drill hole diameter in mm.
            layers: List of layer names the via connects (e.g. ["F.Cu", "B.Cu"]).
            net_name: Net name (e.g. "GND").
            uuid_str: Optional UUID string. If None, a new uuid4 is generated.

        Returns:
            Complete ``(via ...)`` S-expression block (indented, trailing newline).
        """
        if uuid_str is None:
            uuid_str = str(uuid.uuid4())

        x, y = at
        # Quote each layer name and join with single spaces, all inside (layers ...)
        layers_inner = " ".join(f'"{layer}"' for layer in layers)
        parts = [
            "  (via",
            f"    (at {x:g} {y:g})",
            f"    (size {size:g})",
            f"    (drill {drill:g})",
            f"    (layers {layers_inner})",
            f'    (net "{net_name}")',
            f'    (uuid "{uuid_str}")',
            "  )",
        ]
        return "\n".join(parts) + "\n"

    # ------------------------------------------------------------------
    # Delete / move track elements (Phase 101-02)
    # ------------------------------------------------------------------

    @staticmethod
    def _find_block_by_uuid(
        content: str, block_kind: str, uuid_str: str,
    ) -> tuple[Optional[int], Optional[int]]:
        """Find the byte range of a top-level ``(KIND ...)`` block containing uuid.

        Scans for ``(KIND`` block starts (e.g. ``(segment``, ``(via``),
        then uses ``_find_matching_close()`` for correct handling of nested
        parens and quoted strings. Returns the first block whose uuid field
        matches.

        Args:
            content: Raw .kicad_pcb S-expression text.
            block_kind: Block kind keyword without the leading paren
                (e.g. ``"segment"``, ``"via"``, ``"arc"``).
            uuid_str: UUID string to match against ``(uuid "...")`` inside
                the block. Only matches OUTSIDE of quoted strings.

        Returns:
            (start, end) byte offsets with end being the closing paren
            position + 1 (exclusive end), or ``(None, None)`` if not found.
        """
        kind_pat = re.compile(
            r"^[ \t]*\(" + re.escape(block_kind) + r"\b", re.MULTILINE,
        )
        for match in kind_pat.finditer(content):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue
            block = content[start : end + 1]
            # Look for (uuid "...") at the top level of this block. The
            # _find_matching_close already accounts for strings, so a plain
            # substring search for the uuid token is safe here.
            uuid_pat = re.compile(
                r'\(uuid\s+"' + re.escape(uuid_str) + r'"',
            )
            if uuid_pat.search(block):
                return start, end + 1
        return None, None

    @staticmethod
    def delete_segment(content: str, uuid_str: str) -> str:
        """Delete a ``(segment ...)`` block by UUID.

        Walks the content for ``(segment`` blocks and removes the one whose
        ``(uuid "...")`` field matches ``uuid_str``. The leading whitespace
        (newline + indentation) is also removed so the file stays tidy.

        Args:
            content: Raw .kicad_pcb S-expression text.
            uuid_str: UUID of the segment to delete.

        Returns:
            Modified content with the segment block removed.

        Raises:
            ValueError: If no segment with the given UUID is found.
        """
        start, end = PcbRawWriter._find_block_by_uuid(content, "segment", uuid_str)
        if start is None or end is None:
            raise ValueError(f"Segment with UUID '{uuid_str}' not found")

        trim_start = start
        if trim_start > 0 and content[trim_start - 1] == "\n":
            trim_start -= 1
        return content[:trim_start] + content[end:]

    @staticmethod
    def delete_via(content: str, uuid_str: str) -> str:
        """Delete a ``(via ...)`` block by UUID.

        Same algorithm as ``delete_segment`` but for via blocks.

        Args:
            content: Raw .kicad_pcb S-expression text.
            uuid_str: UUID of the via to delete.

        Returns:
            Modified content with the via block removed.

        Raises:
            ValueError: If no via with the given UUID is found.
        """
        start, end = PcbRawWriter._find_block_by_uuid(content, "via", uuid_str)
        if start is None or end is None:
            raise ValueError(f"Via with UUID '{uuid_str}' not found")

        trim_start = start
        if trim_start > 0 and content[trim_start - 1] == "\n":
            trim_start -= 1
        return content[:trim_start] + content[end:]

    @staticmethod
    def move_segment_endpoint(
        content: str,
        uuid_str: str,
        end_kind: str,
        to_xy: tuple[float, float] | list[float],
    ) -> str:
        """Move the start or end point of a ``(segment ...)`` block.

        Finds the segment by UUID, then rewrites its ``(start X Y)`` or
        ``(end X Y)`` field with the new coordinates. Coordinates are
        formatted with ``%g`` to match the rest of Phase 101-01.

        Args:
            content: Raw .kicad_pcb S-expression text.
            uuid_str: UUID of the segment to modify.
            end_kind: Either ``"start"`` or ``"end"`` -- which endpoint
                to move.
            to_xy: New ``(x, y)`` coordinates in mm.

        Returns:
            Modified content with the endpoint moved.

        Raises:
            ValueError: If ``end_kind`` is invalid, the segment UUID is
                not found, or the segment block has no matching
                ``(start ...)`` / ``(end ...)`` field.
        """
        if end_kind not in ("start", "end"):
            raise ValueError(
                f"end_kind must be 'start' or 'end', got {end_kind!r}",
            )

        start, end = PcbRawWriter._find_block_by_uuid(content, "segment", uuid_str)
        if start is None or end is None:
            raise ValueError(f"Segment with UUID '{uuid_str}' not found")

        block = content[start:end]
        x, y = to_xy
        new_field = f"({end_kind} {x:g} {y:g})"

        field_pat = re.compile(
            r"\(" + end_kind + r"\s+[-0-9.]+\s+[-0-9.]+\s*\)",
        )
        match = field_pat.search(block)
        if match is None:
            raise ValueError(
                f"Segment {uuid_str!r} has no ({end_kind} X Y) field",
            )

        new_block = block[: match.start()] + new_field + block[match.end() :]
        return content[:start] + new_block + content[end:]

    # ------------------------------------------------------------------
    # Lock track / via + stitching via pattern (Phase 101-03)
    # ------------------------------------------------------------------

    @staticmethod
    def lock_segment(content: str, uuid_str: str) -> str:
        """Lock a ``(segment ...)`` block by UUID.

        Adds the ``(locked)`` token as the first property inside the segment
        block, immediately after ``(segment``. KiCad 10 format is
        ``(segment (locked) (start ...) (end ...) ...)`` -- locked MUST
        precede the other properties so pcbnew recognizes it.

        H1 (council): No real ``(locked)`` example was found in
        ``/Users/bretbouchard/apps/analog-ecosystem/hardware/`` or in KiCad
        template files -- only ``(unlocked yes)`` pad fields. The canonical
        KiCad 10 form per the file format documentation is used.

        Idempotent: if the segment already contains ``(locked)`` the content
        is returned unchanged.

        Args:
            content: Raw .kicad_pcb S-expression text.
            uuid_str: UUID of the segment to lock.

        Returns:
            Modified content with ``(locked)`` injected as the first property.

        Raises:
            ValueError: If no segment with the given UUID is found.
        """
        start, end = PcbRawWriter._find_block_by_uuid(content, "segment", uuid_str)
        if start is None or end is None:
            raise ValueError(f"Segment with UUID '{uuid_str}' not found")

        return PcbRawWriter._inject_locked_token(content, start, end)

    @staticmethod
    def lock_via(content: str, uuid_str: str) -> str:
        """Lock a ``(via ...)`` block by UUID.

        Adds the ``(locked)`` token as the first property inside the via
        block. Same algorithm as ``lock_segment`` but for vias.

        Args:
            content: Raw .kicad_pcb S-expression text.
            uuid_str: UUID of the via to lock.

        Returns:
            Modified content with ``(locked)`` injected as the first property.

        Raises:
            ValueError: If no via with the given UUID is found.
        """
        start, end = PcbRawWriter._find_block_by_uuid(content, "via", uuid_str)
        if start is None or end is None:
            raise ValueError(f"Via with UUID '{uuid_str}' not found")

        return PcbRawWriter._inject_locked_token(content, start, end)

    @staticmethod
    def _inject_locked_token(
        content: str, block_start: int, block_end: int,
    ) -> str:
        """Inject ``(locked)`` immediately after the opening block token.

        Locates the first whitespace gap after ``(KIND`` and inserts
        ``(locked) `` there. If the block already contains ``(locked)``
        anywhere at the top level, returns content unchanged (idempotent).

        Args:
            content: Raw .kicad_pcb S-expression text.
            block_start: Byte offset of the opening paren of the block.
            block_end: Byte offset one past the closing paren.

        Returns:
            Modified content with ``(locked)`` injected as the first property.
        """
        block = content[block_start:block_end]

        # Idempotent: detect existing (locked) token at top level.
        # Use a regex anchored to the start of the block (right after the
        # opening kind token) so we don't false-positive on nested locks
        # (segments don't have nested locked, but defensive).
        if re.search(r"^\s*\([a-z]+\s+\(locked\)", block):
            return content

        # Find end of the ``(kind`` token -- first whitespace or ')' after
        # the opening paren. We insert `` (locked)`` immediately after the
        # kind keyword.
        kind_match = re.match(r"^(\s*\([a-z]+)(\s+|\))", block)
        if not kind_match:
            # Defensive: malformed block, return unchanged
            return content

        insert_pos_in_block = kind_match.end(1)
        injection = " (locked)"
        new_block = (
            block[:insert_pos_in_block]
            + injection
            + block[insert_pos_in_block:]
        )
        return content[:block_start] + new_block + content[block_end:]

    @staticmethod
    def build_stitching_via_pattern(
        net_name: str,
        region: tuple[tuple[float, float], tuple[float, float]] | list,
        grid_spacing: float,
        size: float = 0.4,
        drill: float = 0.2,
        layers: list[str] | None = None,
    ) -> str:
        """Build a grid of stitching vias as a single S-expression string.

        Generates vias on a regular grid bounded by ``region`` using
        ``build_via_sexp(...)`` from Phase 101-01. Each via gets a fresh
        UUID via ``uuid.uuid4()`` so uniqueness is guaranteed.

        Args:
            net_name: Net name for all vias (e.g. "GND").
            region: ``(corner1, corner2)`` where each corner is ``(x, y)`` in mm.
                ``corner1`` is the min corner, ``corner2`` is the max corner.
            grid_spacing: Spacing between adjacent vias in mm.
            size: Via pad diameter in mm.
            drill: Via drill hole diameter in mm.
            layers: List of layer names the vias connect (default F.Cu + B.Cu).

        Returns:
            Newline-joined ``(via ...)`` blocks ready for ``insert_segments``.
        """
        if layers is None:
            layers = ["F.Cu", "B.Cu"]

        x_min, y_min = region[0]
        x_max, y_max = region[1]

        # Normalize in case caller flipped min/max
        if x_min > x_max:
            x_min, x_max = x_max, x_min
        if y_min > y_max:
            y_min, y_max = y_max, y_min

        blocks: list[str] = []
        x = x_min
        while x <= x_max + 1e-9:  # +epsilon for floating-point inclusivity
            y = y_min
            while y <= y_max + 1e-9:
                block = PcbRawWriter.build_via_sexp(
                    at=(x, y),
                    size=size,
                    drill=drill,
                    layers=layers,
                    net_name=net_name,
                )
                blocks.append(block)
                y += grid_spacing
            x += grid_spacing

        return "\n".join(blocks)

    # ------------------------------------------------------------------
    # Footprint update (#40 migration)
    # ------------------------------------------------------------------

    @staticmethod
    def update_footprint(
        content: str,
        reference: str,
        new_fp_sexpr: str,
    ) -> str:
        """Replace a footprint block with new content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            reference: Reference designator of the footprint to replace.
            new_fp_sexpr: New footprint S-expression (unindented).

        Returns:
            Modified content string, or original if footprint not found.
        """
        start, end = PcbRawWriter._find_footprint_block(content, reference)
        if start is None or end is None:
            return content

        # Preserve original indentation from the line containing the footprint
        line_start = content.rfind("\n", 0, start) + 1
        # indent = whitespace from line start to the opening paren of (footprint
        fp_open = content.index("(", line_start)
        indent = content[line_start:fp_open]
        new_fp_indented = indent + new_fp_sexpr.replace("\n", "\n" + indent)
        return content[:start] + new_fp_indented + content[end:]

    # ------------------------------------------------------------------
    # Title block metadata (Phase 205 — META-02, META-03, META-06)
    # ------------------------------------------------------------------

    @staticmethod
    def set_title_block_fields(
        content: str,
        title: Optional[str] = None,
        date: Optional[str] = None,
        rev: Optional[str] = None,
        company: Optional[str] = None,
        comments: Optional[list[str]] = None,
    ) -> str:
        """Set title_block fields in PCB content. None fields are left unchanged.

        Reads existing title_block values first (to support partial update),
        then rebuilds the entire block. If no title_block exists, inserts one
        after the (paper ...) line (title_block comes after paper, before layers).

        Uses block-level replacement to avoid partial-update edge cases with
        non-sequential comments.
        """
        import sexpdata
        from kicad_agent.parser.pcb_native_parser import (
            _find_string_child,
            _find_symbol,
            _sym,
        )

        # Read existing title_block values for partial update
        existing_title = ""
        existing_date = ""
        existing_rev = ""
        existing_company = ""
        existing_comments: list[str] = []
        try:
            tree = sexpdata.loads(content)
            tb = _find_symbol(tree, "title_block")
            if tb is not None:
                existing_title = _find_string_child(tb, "title")
                existing_date = _find_string_child(tb, "date")
                existing_rev = _find_string_child(tb, "rev")
                existing_company = _find_string_child(tb, "company")
                comments_map: dict[int, str] = {}
                for item in tb:
                    if isinstance(item, list) and len(item) >= 3 and _sym(item[0]) == "comment":
                        try:
                            num = int(item[1])
                            text = item[2] if isinstance(item[2], str) else str(item[2])
                            comments_map[num] = text
                        except (ValueError, TypeError):
                            continue
                if comments_map:
                    max_n = max(comments_map)
                    existing_comments = [comments_map.get(i, "") for i in range(1, max_n + 1)]
        except (ValueError, IndexError, TypeError):
            # If existing title_block can't be parsed, use empty defaults.
            # Narrowed from bare Exception (Council M-3): only catch realistic
            # parse-failure modes, not KeyboardInterrupt/SystemExit.
            pass

        # Apply partial updates (None = keep existing)
        new_title = existing_title if title is None else title
        new_date = existing_date if date is None else date
        new_rev = existing_rev if rev is None else rev
        new_company = existing_company if company is None else company
        new_comments = existing_comments if comments is None else comments

        # Build new title_block S-expression
        def _escape_kicad_string(s: str) -> str:
            """Escape a string for KiCad S-expression: double internal quotes."""
            return s.replace('"', '""')

        lines = ["  (title_block"]
        lines.append(f'    (title "{_escape_kicad_string(new_title)}")')
        lines.append(f'    (date "{_escape_kicad_string(new_date)}")')
        lines.append(f'    (rev "{_escape_kicad_string(new_rev)}")')
        lines.append(f'    (company "{_escape_kicad_string(new_company)}")')
        for i, c in enumerate(new_comments):
            lines.append(f'    (comment {i + 1} "{_escape_kicad_string(c)}")')
        lines.append("  )")
        new_block = "\n".join(lines)

        # Find existing title_block and replace it, or insert new one
        # Anchored to line start to avoid false-matching inside quoted string values
        match = re.search(r"^[ \t]*\(title_block\b", content, re.MULTILINE)
        if match:
            start = match.start()
            # _find_matching_close expects the position of the opening "("
            # itself (depth starts at 0, first "(" -> depth 1, matching
            # ")" -> depth 0). Passing start+1 would skip the "(" and
            # return at the first inner closing paren.
            end = PcbRawWriter._find_matching_close(content, start)
            if end is not None:
                return content[:start] + new_block + content[end + 1:]

        # No existing title_block — insert after (paper ...) element
        paper_match = re.search(r"\(paper\b[^)]*\)", content)
        if paper_match:
            insert_pos = paper_match.end()
            return content[:insert_pos] + "\n" + new_block + content[insert_pos:]

        # No (paper ...) either — insert right after the (kicad_pcb opening
        kicad_match = re.search(r"\(kicad_pcb\b", content)
        if kicad_match:
            insert_pos = kicad_match.end()
            return content[:insert_pos] + "\n" + new_block + content[insert_pos:]

        return content  # Fallback: no change

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _find_matching_close(content: str, open_pos: int) -> Optional[int]:
        """Find the matching closing paren for an S-expression.

        Handles nested parens and quoted strings using KiCad's doubled-quote
        escaping convention (``""`` inside a string represents a literal quote).

        Args:
            content: Raw S-expression text.
            open_pos: Position of the opening paren.

        Returns:
            Position of the matching close paren, or None.
        """
        depth = 0
        i = open_pos
        in_string = False

        while i < len(content):
            c = content[i]
            if in_string:
                if c == '"':
                    # KiCad doubled-quote escape: "" inside string = literal "
                    if i + 1 < len(content) and content[i + 1] == '"':
                        i += 2
                        continue
                    in_string = False
                i += 1
                continue
            if c == '"':
                in_string = True
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    return i
            i += 1
        return None

    @staticmethod
    def _find_footprint_block(
        content: str, reference: str
    ) -> tuple[Optional[int], Optional[int]]:
        """Find the start and end positions of a footprint block by reference.

        Scans for ``(footprint ...`` blocks and checks their Reference property.

        Args:
            content: Raw .kicad_pcb S-expression text.
            reference: Reference designator to find.

        Returns:
            (start, end) byte offsets, or (None, None) if not found.
        """
        for match in re.finditer(r"^[ \t]+\(footprint ", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue

            block = content[start : end + 1]
            ref_match = re.search(
                r'\(property "Reference" "' + re.escape(reference) + r'"',
                block,
            )
            if ref_match:
                return start, end + 1

        return None, None

    @staticmethod
    def extract_footprint_extent(
        content: str, reference: str
    ) -> tuple[float, float] | None:
        """Extract pad bounding box for a footprint, returned as (width, height).

        Scans all ``(pad ...)`` blocks within the target footprint and
        computes the bounding box of all pad extents in local coordinates.

        Args:
            content: Raw .kicad_pcb S-expression text.
            reference: Reference designator to find.

        Returns:
            (width, height) in mm, or None if not found.
        """
        start, end = PcbRawWriter._find_footprint_block(content, reference)
        if start is None or end is None:
            return None

        block = content[start:end]

        # Extract all pad blocks
        pad_positions: list[float] = []
        for pad_m in re.finditer(r"\(pad\s", block):
            pad_start = pad_m.start()
            pad_end = PcbRawWriter._find_matching_close(block, pad_start)
            if pad_end is None:
                continue
            pad_block = block[pad_start:pad_end + 1]

            # Extract (at X Y [angle])
            at_m = re.search(r"\(at\s+([-\d.]+)\s+([-\d.]+)", pad_block)
            if not at_m:
                continue
            px, py = float(at_m.group(1)), float(at_m.group(2))

            # Extract (size W H)
            size_m = re.search(r"\(size\s+([-\d.]+)\s+([-\d.]+)", pad_block)
            if not size_m:
                continue
            pw, ph = float(size_m.group(1)), float(size_m.group(2))

            pad_positions.append(px - pw / 2)
            pad_positions.append(py - ph / 2)
            pad_positions.append(px + pw / 2)
            pad_positions.append(py + ph / 2)

        if not pad_positions:
            return None

        x_min = min(pad_positions[0::4])
        y_min = min(pad_positions[1::4])
        x_max = max(pad_positions[2::4])
        y_max = max(pad_positions[3::4])

        width = max(0.5, x_max - x_min)
        height = max(0.5, y_max - y_min)
        return (round(width, 3), round(height, 3))

    @staticmethod
    def build_exclusion_zones(
        content: str,
        refs: list[str],
        margin: float = 3.0,
    ) -> list[tuple[float, float, float, float]]:
        """Build AABB exclusion zones around specified footprints.

        For each reference, extracts its pad extent and board position,
        then creates a rectangle (with margin) that other components
        should not overlap during placement.

        Args:
            content: Raw .kicad_pcb S-expression text.
            refs: References to build exclusion zones around.
            margin: Extra margin in mm beyond the pad extent.

        Returns:
            List of (x1, y1, x2, y2) exclusion rectangles.
        """
        exclusions: list[tuple[float, float, float, float]] = []
        for ref in refs:
            start, end = PcbRawWriter._find_footprint_block(content, ref)
            if start is None or end is None:
                continue
            block = content[start:end]

            # Get footprint position
            at_m = re.search(
                r"^\s*\(at\s+([-\d.]+)\s+([-\d.]+)", block, re.MULTILINE
            )
            if not at_m:
                continue
            fx, fy = float(at_m.group(1)), float(at_m.group(2))

            # Get pad extent in local coords
            extent = PcbRawWriter.extract_footprint_extent(content, ref)
            if extent:
                pw, ph = extent
            else:
                pw, ph = 2.0, 2.0

            # AABB: footprint position is center-ish, pad extent is local
            # Conservative: use footprint origin as center of pad extent
            x1 = fx - pw / 2 - margin
            y1 = fy - ph / 2 - margin
            x2 = fx + pw / 2 + margin
            y2 = fy + ph / 2 + margin
            exclusions.append((x1, y1, x2, y2))

        return exclusions

    @staticmethod
    def batch_expand_footprints(
        content: str,
        pcb_path: Path,
        dry_run: bool = False,
    ) -> tuple[str, dict]:
        """Expand all synthetic (geometry-less) footprints from libraries.

        Scans all footprint blocks, identifies those without ``(pad ...)``
        lines, resolves their lib_id to .kicad_mod files, and replaces them
        with full geometry while preserving position, rotation, net assignments.

        Args:
            content: Raw .kicad_pcb S-expression text.
            pcb_path: Path to the .kicad_pcb file (for lib resolution).
            dry_run: If True, report counts without modifying content.

        Returns:
            (modified_content, result_dict) with expansion statistics.
        """
        from kicad_agent.lib_resolver import resolve_footprint_path

        expanded = 0
        failed = 0
        skipped = 0
        errors = []

        # Collect all footprint blocks and their positions
        blocks = []
        for match in re.finditer(r"^[ \t]+\(footprint ", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue
            blocks.append((start, end + 1, content[start : end + 1]))

        # Identify synthetic footprints (no pad lines)
        synthetic_blocks = []
        for start, end, block in blocks:
            if "(pad " not in block:
                synthetic_blocks.append((start, end, block))

        if not synthetic_blocks:
            return content, {
                "expanded": 0,
                "failed": 0,
                "skipped": len(blocks),
                "total_footprints": len(blocks),
                "errors": [],
            }

        if dry_run:
            return content, {
                "expanded": 0,
                "failed": 0,
                "skipped": len(blocks) - len(synthetic_blocks),
                "total_footprints": len(blocks),
                "synthetic_found": len(synthetic_blocks),
                "errors": [],
            }

        # Process blocks from bottom to top to preserve offsets
        synthetic_blocks.sort(key=lambda b: b[0], reverse=True)
        new_content = content

        for start, end, block in synthetic_blocks:
            # Extract lib_id — try (lib_id "...") field first,
            # then fall back to (footprint "LIB:FP" ...) KiCad 10 format
            lib_id_match = re.search(r'\(lib_id "([^"]+)"', block)
            if not lib_id_match:
                lib_id_match = re.search(
                    r'\(footprint "([^"]+)"', block
                )
            if not lib_id_match:
                failed += 1
                errors.append(f"No lib_id found in block at offset {start}")
                continue

            lib_id = lib_id_match.group(1)

            # Extract reference for error reporting
            ref_match = re.search(r'\(property "Reference" "([^"]+)"', block)
            ref = ref_match.group(1) if ref_match else "unknown"

            # Extract preserved placement fields
            at_match = re.search(r'\(at ([\d.\-]+) ([\d.\-]+)(?: ([\d.\-]+))?\)', block)
            layer_match = re.search(r'\(layer "([^"]+)"', block)
            tstamp_match = re.search(r'\(tstamp "([^"]+)"', block)
            uuid_match = re.search(r'\(uuid "([^"]+)"', block)

            # Resolve library path
            try:
                mod_path = resolve_footprint_path(lib_id, pcb_path)
            except (ValueError, FileNotFoundError) as e:
                failed += 1
                errors.append(f"{ref}: cannot resolve '{lib_id}': {e}")
                continue

            # Read library footprint
            try:
                lib_content = mod_path.read_text(encoding="utf-8")
            except Exception as e:
                failed += 1
                errors.append(f"{ref}: cannot read '{mod_path}': {e}")
                continue

            # Strip library-only metadata
            lib_content = _strip_library_metadata(lib_content)

            # Extract pad net assignments from synthetic block (if any)
            pad_nets = {}
            for pm in re.finditer(
                r'\(pad "(\d+)"[^)]*\(net (\d+) "([^"]+)"', block
            ):
                pad_nets[pm.group(1)] = (pm.group(2), pm.group(3))

            # Inject preserved placement data into library content.
            # The .kicad_mod file uses \t indentation — preserve it.
            # Note: library footprints may not have a top-level (at ...) line,
            # so we insert after (layer ...) if no existing (at ...) is found.
            if at_match:
                at_sexpr = f"\t(at {at_match.group(1)} {at_match.group(2)}"
                if at_match.group(3):
                    at_sexpr += f" {at_match.group(3)}"
                at_sexpr += ")"
                existing_at = re.search(r"^\t\(at [^\)]*\)", lib_content, flags=re.MULTILINE)
                if existing_at:
                    lib_content = (
                        lib_content[: existing_at.start()]
                        + at_sexpr
                        + lib_content[existing_at.end() :]
                    )
                else:
                    # Insert after (layer ...) line
                    lib_content = _insert_after_field(
                        lib_content,
                        r'^\t\(layer "[^"]*"\)',
                        "\n" + at_sexpr,
                    )

            # Preserve layer
            if layer_match:
                lib_content = re.sub(
                    r'^\t\(layer "[^"]*"\)',
                    f'\t(layer "{layer_match.group(1)}")',
                    lib_content,
                    count=1,
                    flags=re.MULTILINE,
                )

            # Add tstamp/uuid (KiCad 10 format)
            if tstamp_match:
                lib_content = _insert_after_field(
                    lib_content,
                    r'^\t\(layer "[^"]*"\)',
                    f'\n\t(tstamp "{tstamp_match.group(1)}")',
                )
            elif uuid_match:
                lib_content = _insert_after_field(
                    lib_content,
                    r'^\t\(layer "[^"]*"\)',
                    f'\n\t(uuid "{uuid_match.group(1)}")',
                )

            # Preserve reference and value properties
            ref_prop = re.search(r'\(property "Reference" "([^"]+)"', block)
            val_prop = re.search(r'\(property "Value" "([^"]+)"', block)
            if ref_prop:
                lib_content = re.sub(
                    r'\t\(property "Reference" "[^"]*"',
                    f'\t(property "Reference" "{ref_prop.group(1)}"',
                    lib_content,
                    count=1,
                )
            if val_prop:
                lib_content = re.sub(
                    r'\t\(property "Value" "[^"]*"',
                    f'\t(property "Value" "{val_prop.group(1)}"',
                    lib_content,
                    count=1,
                )

            # Re-inject pad net assignments using balanced-paren matching
            for pad_num, (net_id, net_name) in pad_nets.items():
                pad_start = _find_pad_block(lib_content, pad_num)
                if pad_start is not None:
                    pad_end = PcbRawWriter._find_matching_close(lib_content, pad_start)
                    if pad_end is not None:
                        pad_block = lib_content[pad_start:pad_end + 1]
                        lib_content = (
                            lib_content[:pad_start]
                            + _inject_pad_net(pad_block, net_id, net_name)
                            + lib_content[pad_end + 1:]
                        )

            # Preserve original indentation
            line_start = content.rfind("\n", 0, start) + 1
            fp_open = content.index("(", line_start)
            indent = content[line_start:fp_open]
            indented_lib = indent + lib_content.replace("\n", "\n" + indent)

            new_content = new_content[:start] + indented_lib + new_content[end:]
            expanded += 1

        return new_content, {
            "expanded": expanded,
            "failed": failed,
            "skipped": len(blocks) - len(synthetic_blocks),
            "total_footprints": len(blocks),
            "errors": errors,
        }



    # ------------------------------------------------------------------
    # Component placement (Phase 101-05)
    # ------------------------------------------------------------------

    # Parametric SMD footprint library (Option A).
    # Pad geometry per IPC-7351 nominal for common 0402/0603/0805 packages.
    # Each entry yields pad_width, pad_height, pad_pitch (center-to-center).
    # Source: IPC-SM-782 / KiCad standard footprint libraries.
    _SMD_FOOTPRINT_LIBRARY = {
        "Capacitor_SMD:C_0402_1005Metric": {
            "pad_width": 0.56, "pad_height": 0.50, "pad_pitch": 0.44,
            "descr": "Capacitor SMD 0402 (1005 Metric), IPC-7351 nominal",
            "tags": "capacitor",
        },
        "Capacitor_SMD:C_0603_1608Metric": {
            "pad_width": 0.80, "pad_height": 0.95, "pad_pitch": 0.80,
            "descr": "Capacitor SMD 0603 (1608 Metric), IPC-7351 nominal",
            "tags": "capacitor",
        },
        "Capacitor_SMD:C_0805_2012Metric": {
            "pad_width": 1.05, "pad_height": 1.25, "pad_pitch": 0.95,
            "descr": "Capacitor SMD 0805 (2012 Metric), IPC-7351 nominal",
            "tags": "capacitor",
        },
        "Resistor_SMD:R_0402_1005Metric": {
            "pad_width": 0.56, "pad_height": 0.50, "pad_pitch": 0.44,
            "descr": "Resistor SMD 0402 (1005 Metric), IPC-7351 nominal",
            "tags": "resistor",
        },
        "Resistor_SMD:R_0603_1608Metric": {
            "pad_width": 0.80, "pad_height": 0.95, "pad_pitch": 0.80,
            "descr": "Resistor SMD 0603 (1608 Metric), IPC-7351 nominal",
            "tags": "resistor",
        },
        "Resistor_SMD:R_0805_2012Metric": {
            "pad_width": 1.05, "pad_height": 1.25, "pad_pitch": 0.95,
            "descr": "Resistor SMD 0805 (2012 Metric), IPC-7351 nominal",
            "tags": "resistor",
        },
    }

    @staticmethod
    def list_supported_footprints():
        """Return the list of supported footprint library IDs (Option A).

        Unsupported IDs should raise ValueError from build_footprint_sexp.
        Loading footprints from an installed KiCad library (Option B) is
        a future enhancement.
        """
        return sorted(PcbRawWriter._SMD_FOOTPRINT_LIBRARY.keys())

    @staticmethod
    def build_footprint_sexp(
        footprint_id,
        ref,
        value,
        at,
        layer="F.Cu",
        rotation=0.0,
        net_pad_map=None,
    ):
        """Build a KiCad 10 ``(footprint ...)`` S-expression for an SMD passive.

        Uses the parametric ``_SMD_FOOTPRINT_LIBRARY`` (Option A) for common
        0402/0603/0805 cap and resistor packages. Pads use the KiCad 10
        string-only ``(net "NAME")`` net reference.

        The footprint name embedded in the PCB is the bare footprint name
        (the part after the colon in the library ID), matching the format
        KiCad itself writes when syncing from schematic.

        Args:
            footprint_id: Library ID, e.g. "Capacitor_SMD:C_0402_1005Metric".
            ref: Reference designator, e.g. "C42".
            value: Value string (typically "" for caps, "100" for resistors).
            at: (x, y) position in mm.
            layer: "F.Cu" or "B.Cu". B.Cu mirrors pad X coordinates and
                swaps to B-prefixed layers.
            rotation: Rotation in degrees (default 0).
            net_pad_map: Mapping of pad number to net name. Pads not in the
                map are emitted without a ``(net ...)`` field (unconnected).

        Returns:
            Complete ``(footprint ...)`` S-expression block (indented,
            trailing newline).

        Raises:
            ValueError: If ``footprint_id`` is not in the parametric library.
        """
        if footprint_id not in PcbRawWriter._SMD_FOOTPRINT_LIBRARY:
            supported = ", ".join(PcbRawWriter.list_supported_footprints())
            raise ValueError(
                "Unsupported footprint: " + repr(footprint_id) +
                ". Parametric library (Option A) supports only: " + supported +
                ". Loading arbitrary footprints from installed KiCad libraries "
                "(Option B) is a future enhancement."
            )

        if net_pad_map is None:
            net_pad_map = {}

        geom = PcbRawWriter._SMD_FOOTPRINT_LIBRARY[footprint_id]
        pad_w = geom["pad_width"]
        pad_h = geom["pad_height"]
        pad_pitch = geom["pad_pitch"]
        descr = geom["descr"]
        tags = geom["tags"]

        # Bare footprint name (after the colon). KiCad embeds without lib prefix.
        if ":" in footprint_id:
            fp_name = footprint_id.split(":", 1)[1]
        else:
            fp_name = footprint_id

        x, y = at
        is_bottom = (layer == "B.Cu")

        # Layer names for pads differ between F.Cu and B.Cu
        if is_bottom:
            pad_layers = "\"B.Cu\" \"B.Mask\" \"B.Paste\""
            silk_layer = "B.SilkS"
            fab_layer = "B.Fab"
        else:
            pad_layers = "\"F.Cu\" \"F.Mask\" \"F.Paste\""
            silk_layer = "F.SilkS"
            fab_layer = "F.Fab"

        # Pad X coords are symmetric regardless of layer
        pad1_x = -pad_pitch / 2.0
        pad2_x = pad_pitch / 2.0

        # (at X Y) or (at X Y ANGLE)
        if abs(rotation) < 1e-9:
            at_line = "(at " + format(x, "g") + " " + format(y, "g") + ")"
        else:
            at_line = ("(at " + format(x, "g") + " " + format(y, "g")
                       + " " + format(rotation, "g") + ")")

        # Generate unique UUIDs for each element that needs one
        fp_uuid = str(uuid.uuid4())
        ref_uuid = str(uuid.uuid4())
        val_uuid = str(uuid.uuid4())
        pad1_uuid = str(uuid.uuid4())
        pad2_uuid = str(uuid.uuid4())

        lines = []
        lines.append("\t(footprint \"" + fp_name + "\"")
        lines.append("\t\t(layer \"" + layer + "\")")
        lines.append("\t\t(uuid \"" + fp_uuid + "\")")
        lines.append("\t\t" + at_line)
        lines.append("\t\t(descr \"" + descr + "\")")
        lines.append("\t\t(tags \"" + tags + "\")")

        # Reference property
        lines.append("\t\t(property \"Reference\" \"" + ref + "\"")
        lines.append("\t\t\t(at 0 -1.5 0)")
        lines.append("\t\t\t(layer \"" + silk_layer + "\")")
        lines.append("\t\t\t(uuid \"" + ref_uuid + "\")")
        lines.append("\t\t\t(effects")
        lines.append("\t\t\t\t(font")
        lines.append("\t\t\t\t\t(size 1 1)")
        lines.append("\t\t\t\t\t(thickness 0.15)")
        lines.append("\t\t\t\t)")
        lines.append("\t\t\t)")
        lines.append("\t\t)")

        # Value property
        lines.append("\t\t(property \"Value\" \"" + value + "\"")
        lines.append("\t\t\t(at 0 1.5 0)")
        lines.append("\t\t\t(layer \"" + fab_layer + "\")")
        lines.append("\t\t\t(uuid \"" + val_uuid + "\")")
        lines.append("\t\t\t(effects")
        lines.append("\t\t\t\t(font")
        lines.append("\t\t\t\t\t(size 1 1)")
        lines.append("\t\t\t\t\t(thickness 0.15)")
        lines.append("\t\t\t\t)")
        lines.append("\t\t\t)")
        lines.append("\t\t)")

        # attr smd
        lines.append("\t\t(attr smd)")

        # Pad 1
        lines.append("\t\t(pad \"1\" smd roundrect")
        lines.append("\t\t\t(at " + format(pad1_x, "g") + " 0)")
        lines.append("\t\t\t(size " + format(pad_w, "g") + " " + format(pad_h, "g") + ")")
        lines.append("\t\t\t(layers " + pad_layers + ")")
        lines.append("\t\t\t(roundrect_rratio 0.25)")
        if "1" in net_pad_map:
            lines.append("\t\t\t(net \"" + net_pad_map["1"] + "\")")
        lines.append("\t\t\t(uuid \"" + pad1_uuid + "\")")
        lines.append("\t\t)")

        # Pad 2
        lines.append("\t\t(pad \"2\" smd roundrect")
        lines.append("\t\t\t(at " + format(pad2_x, "g") + " 0)")
        lines.append("\t\t\t(size " + format(pad_w, "g") + " " + format(pad_h, "g") + ")")
        lines.append("\t\t\t(layers " + pad_layers + ")")
        lines.append("\t\t\t(roundrect_rratio 0.25)")
        if "2" in net_pad_map:
            lines.append("\t\t\t(net \"" + net_pad_map["2"] + "\")")
        lines.append("\t\t\t(uuid \"" + pad2_uuid + "\")")
        lines.append("\t\t)")

        # Close footprint
        lines.append("\t)")

        return "\n".join(lines) + "\n"




def _strip_library_metadata(sexp: str) -> str:
    """Remove library-only fields from a .kicad_mod file for PCB embedding."""
    for pattern in [
        r"^\t?\(version [^\)]*\)\s*\n",
        r'^\t?\(generator "[^"]*"\)\s*\n',
        r'^\t?\(generator_version "[^"]*"\)\s*\n',
        r'^\t?\(compatibility "[^"]*"\s*\([^)]*\)\)\s*\n',
        r'^\t\(descr ".*"\)\s*\n',
        r'^\t\(tags ".*"\)\s*\n',
    ]:
        sexp = re.sub(pattern, "", sexp, flags=re.MULTILINE)
    return sexp


def _insert_after_field(sexp: str, field_pattern: str, insertion: str) -> str:
    """Insert text after the line matching field_pattern."""
    match = re.search(field_pattern, sexp, re.MULTILINE)
    if match:
        end = match.end()
        sexp = sexp[:end] + insertion + sexp[end:]
    return sexp


def _find_pad_block(content: str, pad_num: str) -> int | None:
    """Find the start offset of a pad block by pad number."""
    m = re.search(r'\(pad "' + re.escape(pad_num) + r'"', content)
    return m.start() if m else None


def _inject_pad_net(pad_sexpr: str, net_id: str, net_name: str) -> str:
    """Inject or replace net assignment in a pad S-expression.

    The pad_sexpr is the full balanced-paren pad block including
    the opening (pad ... and closing ).
    """
    if "(net " in pad_sexpr:
        return re.sub(
            r'\(net \d+ "[^"]*"\)',
            f'(net {net_id} "{net_name}")',
            pad_sexpr,
            count=1,
        )
    else:
        # Insert net before the final closing paren
        return pad_sexpr.rstrip().rstrip(")") + f' (net {net_id} "{net_name}")\n\t)'
