"""PcbRawWriter -- centralized raw S-expression manipulation for PCB files.

All methods return modified content strings (Council C-01). The caller
(executor or handler) is responsible for writing to disk via atomic
temp+rename and cache invalidation.

Consolidates raw-write sites (Council C-02):
- insert_track_segments (was in ir/pcb_ir.py)
- assign_net_class (was in ops/pcb_ops.py)
- update_footprint (was in ir/pcb_ir.py)
- insert_zone (new for #38)
- modify_footprint_position (new for #39)

Usage:
    from kicad_agent.ops.pcb_raw_writer import PcbRawWriter

    content = PcbRawWriter.insert_segments(raw, sexpr_blocks)
    content = PcbRawWriter.assign_net_class(raw, net_name, class_name)
"""

import re
from pathlib import Path
from typing import Any, Optional


class PcbRawWriter:
    """Stateless utility class for raw PCB S-expression manipulation.

    Every method takes raw S-expression content and returns new content.
    No method writes to disk or accesses the filesystem.
    """

    # ------------------------------------------------------------------
    # Track segments (#37)
    # ------------------------------------------------------------------

    @staticmethod
    def insert_segments(content: str, sexpr_blocks: str) -> str:
        """Insert track segment S-expressions before the closing paren.

        Args:
            content: Raw .kicad_pcb S-expression text.
            sexpr_blocks: One or more (segment ...) S-expression strings.

        Returns:
            Modified content with segments inserted.
        """
        last_close = content.rfind(")")
        if last_close == -1:
            return content
        insertion = "\n" + sexpr_blocks + "\n"
        return content[:last_close] + insertion + content[last_close:]

    # ------------------------------------------------------------------
    # Copper zone (#38, #65)
    # ------------------------------------------------------------------

    @staticmethod
    def insert_zone(
        content: str,
        zone_sexp: str,
    ) -> str:
        """Insert a copper zone S-expression before the closing paren.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_sexp: Complete (zone ...) S-expression block.

        Returns:
            Modified content with zone inserted.
        """
        last_close = content.rfind(")")
        if last_close == -1:
            return content
        insertion = "\n" + zone_sexp + "\n"
        return content[:last_close] + insertion + content[last_close:]

    @staticmethod
    def build_zone_sexp(
        net_number: int,
        net_name: str,
        layer: str,
        polygon: list[tuple[float, float]],
        clearance: float = 0.5,
        min_thickness: float = 0.25,
        priority: int = 0,
        uuid: str = "00000000-0000-0000-0000-000000000000",
    ) -> str:
        """Build a KiCad copper zone S-expression.

        Generates zones matching the board's file format:
        - Older KiCad (version 20250125): (net N "name") format
        - Newer KiCad (version 20260206): (net "name") format

        KiCad fills (filled_polygon, filled_areas) are auto-generated by
        the zone filler on save -- never included in hand-written zones.

        Fixes #65: proper KiCad 10 S-expression format with quoted UUIDs,
        correct net field, no stub filled_polygon, no invalid fields.

        Args:
            net_number: Net number for the zone.
            net_name: Net name (e.g. "GND").
            layer: Copper layer (e.g. "F.Cu", "B.Cu").
            polygon: Outline polygon as [(x, y), ...].
            clearance: Zone clearance in mm.
            min_thickness: Minimum fill width in mm.
            priority: Zone priority (higher = filled first).
            uuid: Zone UUID (quoted in output per KiCad format).

        Returns:
            Complete (zone ...) S-expression string.
        """
        # Build polygon points as single-line (xy ...) entries
        xy_entries = " ".join(
            f"(xy {x:g} {y:g})" for x, y in polygon
        )

        # Net format: always use (net "name") for zones. KiCad 10+ zones
        # resolve the net name to number internally; using (net N "name")
        # breaks older file formats (version 20250125) which reject numbered
        # net references in zones. Name-only is universal across all versions.
        if net_name:
            net_line = f'(net "{net_name}")'
        else:
            net_line = '(net 0 "")'

        # UUID quoted per KiCad S-expression format
        uuid_line = f'(uuid "{uuid}")'

        parts = [
            '  (zone',
            f'    {net_line}',
            f'    (layer "{layer}")',
            f'    {uuid_line}',
            '    (hatch edge 0.5)',
            '    (connect_pads',
            f'      (clearance {clearance:g})',
            '    )',
            f'    (min_thickness {min_thickness:g})',
            '    (fill yes',
            f'      (thermal_gap {clearance:g})',
            f'      (thermal_bridge_width {clearance:g})',
            '      (island_removal_mode 1)',
            '    )',
            '    (polygon',
            '      (pts',
            f'        {xy_entries}',
            '      )',
            '    )',
            '  )',
        ]

        return "\n".join(parts) + "\n"

    # ------------------------------------------------------------------
    # Zone lifecycle (find, modify, remove) -- Plan 79-03
    # ------------------------------------------------------------------

    @staticmethod
    def find_zone_block(
        content: str, zone_uuid: str,
    ) -> tuple[Optional[int], Optional[int]]:
        """Find a zone block by UUID in raw PCB content.

        Scans for ``(zone`` blocks and checks if the block contains the
        target UUID. Uses ``_find_matching_close()`` for correct handling
        of nested parens (T-79-01).

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID string to search for.

        Returns:
            (start, end) byte offsets, or (None, None) if not found.
        """
        uuid_pat = re.compile(
            r'\(uuid\s+"' + re.escape(zone_uuid) + r'"'
        )
        for match in re.finditer(r"^\s*\(zone\b", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue
            block = content[start : end + 1]
            if uuid_pat.search(block):
                return start, end + 1
        return None, None

    @staticmethod
    def find_zone_block_by_index(
        content: str, index: int,
    ) -> tuple[Optional[int], Optional[int]]:
        """Find the Nth zone block (0-indexed) in raw PCB content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            index: 0-based zone index.

        Returns:
            (start, end) byte offsets, or (None, None) if not found.
        """
        count = 0
        for match in re.finditer(r"^\s*\(zone\b", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue
            if count == index:
                return start, end + 1
            count += 1
        return None, None

    @staticmethod
    def modify_zone_field(
        content: str, zone_uuid: str, field: str, value: Any,
    ) -> str:
        """Modify a single field within a zone block.

        Supported fields: ``net_name``, ``layer``, ``clearance``,
        ``priority``, ``min_width``.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID of the zone to modify.
            field: Field name to change.
            value: New value for the field.

        Returns:
            Modified content, or original if zone not found.
        """
        start, end = PcbRawWriter.find_zone_block(content, zone_uuid)
        if start is None or end is None:
            return content

        block = content[start:end]

        if field == "net_name":
            # D-13 + H-05: Extract existing net number from content before substitution.
            # Do NOT add ir parameter to @staticmethod (API contract).
            existing_net_match = re.search(r'\(net\s+(\d+)\s+"[^"]*"\)', block)
            existing_net_id = int(existing_net_match.group(1)) if existing_net_match else 0
            block = re.sub(
                r'\(net\s+\d+\s+"[^"]*"\)',
                f'(net {existing_net_id} "{value}")',
                block,
                count=1,
            )
        elif field == "layer":
            block = re.sub(
                r'\(layer\s+"[^"]*"\)',
                f'(layer "{value}")',
                block,
                count=1,
            )
        elif field == "clearance":
            # Replace clearance inside (connect_pads ... (clearance X))
            block = re.sub(
                r'\(clearance\s+[-\d.]+\)',
                f'(clearance {value:g})',
                block,
                count=1,
            )
        elif field == "priority":
            if "(priority " in block:
                block = re.sub(
                    r'\(priority\s+\d+\)',
                    f'(priority {value})',
                    block,
                    count=1,
                )
            else:
                # Insert priority after min_thickness line
                block = re.sub(
                    r'(\(min_thickness\s+[-\d.]+\))',
                    f'\\1\n    (priority {value})',
                    block,
                    count=1,
                )
        elif field == "min_width":
            block = re.sub(
                r'\(min_thickness\s+[-\d.]+\)',
                f'(min_thickness {value:g})',
                block,
                count=1,
            )

        return content[:start] + block + content[end:]

    @staticmethod
    def modify_zone_polygon(
        content: str,
        zone_uuid: str,
        polygon: list[tuple[float, float]],
    ) -> str:
        """Replace the polygon outline of a zone block.

        Finds the ``(polygon (pts ...))`` sub-block within the zone and
        replaces the xy entries with new polygon points.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID of the zone to modify.
            polygon: New polygon outline as [(x, y), ...].

        Returns:
            Modified content, or original if zone not found.
        """
        start, end = PcbRawWriter.find_zone_block(content, zone_uuid)
        if start is None or end is None:
            return content

        block = content[start:end]

        xy_entries = " ".join(
            f"(xy {x:g} {y:g})" for x, y in polygon
        )
        new_pts_block = f"        {xy_entries}"

        # Replace content between (pts and closing ))
        block = re.sub(
            r'(\(pts\s*\n).*?(\n\s*\))',
            lambda m: f'(pts\n{new_pts_block}\n      )',
            block,
            count=1,
            flags=re.DOTALL,
        )

        return content[:start] + block + content[end:]

    @staticmethod
    def remove_zone_block(content: str, zone_uuid: str) -> str:
        """Remove a zone block entirely from raw PCB content.

        Removes the zone block including its surrounding whitespace.

        Args:
            content: Raw .kicad_pcb S-expression text.
            zone_uuid: UUID of the zone to remove.

        Returns:
            Modified content with zone removed, or original if not found.
        """
        start, end = PcbRawWriter.find_zone_block(content, zone_uuid)
        if start is None or end is None:
            return content

        # Include leading newline if present
        trim_start = start
        if trim_start > 0 and content[trim_start - 1] == "\n":
            trim_start -= 1

        return content[:trim_start] + content[end:]

    # ------------------------------------------------------------------
    # Net class (#40 migration)
    # ------------------------------------------------------------------

    @staticmethod
    def assign_net_class(
        content: str,
        net_name: str,
        net_class_name: str,
    ) -> str:
        """Add or update a net class assignment in raw PCB content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            net_name: Name of the net to assign.
            net_class_name: Name of the net class.

        Returns:
            Modified content string.
        """
        # Remove this net from any existing net_class blocks
        add_net_pattern = re.compile(
            r'\(add_net "' + re.escape(net_name) + r'"\)\s*\n?'
        )
        content = add_net_pattern.sub("", content)

        # Find or create the target net_class block
        class_pattern = re.compile(
            r'\(net_class "' + re.escape(net_class_name) + r'"'
        )
        match = class_pattern.search(content)
        if match:
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start)
            if end is not None:
                insertion = f'\n      (add_net "{net_name}")'
                content = content[:end] + insertion + content[end:]
        else:
            # Create new net_class block before the first (net ... ) line
            new_class = (
                f'  (net_class "{net_class_name}" ""\n'
                f'    (add_net "{net_name}")\n'
                f'  )\n'
            )
            first_net = re.search(r'\n  \(net \d+ ', content)
            if first_net:
                content = (
                    content[:first_net.start()]
                    + "\n"
                    + new_class
                    + content[first_net.start() :]
                )
            else:
                content = content.rstrip() + "\n" + new_class + ")\n"

        return content

    # ------------------------------------------------------------------
    # Footprint position (#39)
    # ------------------------------------------------------------------

    @staticmethod
    def modify_footprint_position(
        content: str,
        reference: str,
        x: float,
        y: float,
        angle: float = 0.0,
    ) -> str:
        """Move a footprint to a new position in raw PCB content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            reference: Reference designator (e.g. "R1").
            x: New X position in mm.
            y: New Y position in mm.
            angle: New rotation angle in degrees.

        Returns:
            Modified content string, or original if footprint not found.
        """
        start, end = PcbRawWriter._find_footprint_block(content, reference)
        if start is None or end is None:
            return content

        block = content[start:end]

        # Replace (at X Y angle) in the footprint block
        at_pattern = re.compile(
            r'\(at\s+[-\d.]+\s+[-\d.]+(?:\s+[-\d.]+)?\s*\)'
        )
        new_at = f"(at {x:.6f} {y:.6f} {angle:.6f})"
        new_block = at_pattern.sub(new_at, block, count=1)

        return content[:start] + new_block + content[end:]

    # ------------------------------------------------------------------
    # Footprint update (#40 migration)
    # ------------------------------------------------------------------

    @staticmethod
    def update_footprint(
        content: str,
        reference: str,
        new_fp_sexpr: str,
    ) -> str:
        """Replace a footprint block with new content.

        Args:
            content: Raw .kicad_pcb S-expression text.
            reference: Reference designator of the footprint to replace.
            new_fp_sexpr: New footprint S-expression (unindented).

        Returns:
            Modified content string, or original if footprint not found.
        """
        start, end = PcbRawWriter._find_footprint_block(content, reference)
        if start is None or end is None:
            return content

        # Preserve original indentation from the line containing the footprint
        line_start = content.rfind("\n", 0, start) + 1
        # indent = whitespace from line start to the opening paren of (footprint
        fp_open = content.index("(", line_start)
        indent = content[line_start:fp_open]
        new_fp_indented = indent + new_fp_sexpr.replace("\n", "\n" + indent)
        return content[:start] + new_fp_indented + content[end:]

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _find_matching_close(content: str, open_pos: int) -> Optional[int]:
        """Find the matching closing paren for an S-expression.

        Handles nested parens and quoted strings using KiCad's doubled-quote
        escaping convention (``""`` inside a string represents a literal quote).

        Args:
            content: Raw S-expression text.
            open_pos: Position of the opening paren.

        Returns:
            Position of the matching close paren, or None.
        """
        depth = 0
        i = open_pos
        in_string = False

        while i < len(content):
            c = content[i]
            if in_string:
                if c == '"':
                    # KiCad doubled-quote escape: "" inside string = literal "
                    if i + 1 < len(content) and content[i + 1] == '"':
                        i += 2
                        continue
                    in_string = False
                i += 1
                continue
            if c == '"':
                in_string = True
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    return i
            i += 1
        return None

    @staticmethod
    def _find_footprint_block(
        content: str, reference: str
    ) -> tuple[Optional[int], Optional[int]]:
        """Find the start and end positions of a footprint block by reference.

        Scans for ``(footprint ...`` blocks and checks their Reference property.

        Args:
            content: Raw .kicad_pcb S-expression text.
            reference: Reference designator to find.

        Returns:
            (start, end) byte offsets, or (None, None) if not found.
        """
        for match in re.finditer(r"^[ \t]+\(footprint ", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue

            block = content[start : end + 1]
            ref_match = re.search(
                r'\(property "Reference" "' + re.escape(reference) + r'"',
                block,
            )
            if ref_match:
                return start, end + 1

        return None, None

    @staticmethod
    def batch_expand_footprints(
        content: str,
        pcb_path: Path,
        dry_run: bool = False,
    ) -> tuple[str, dict]:
        """Expand all synthetic (geometry-less) footprints from libraries.

        Scans all footprint blocks, identifies those without ``(pad ...)``
        lines, resolves their lib_id to .kicad_mod files, and replaces them
        with full geometry while preserving position, rotation, net assignments.

        Args:
            content: Raw .kicad_pcb S-expression text.
            pcb_path: Path to the .kicad_pcb file (for lib resolution).
            dry_run: If True, report counts without modifying content.

        Returns:
            (modified_content, result_dict) with expansion statistics.
        """
        from kicad_agent.lib_resolver import resolve_footprint_path

        expanded = 0
        failed = 0
        skipped = 0
        errors = []

        # Collect all footprint blocks and their positions
        blocks = []
        for match in re.finditer(r"^[ \t]+\(footprint ", content, re.MULTILINE):
            start = match.start()
            end = PcbRawWriter._find_matching_close(content, start + 1)
            if end is None:
                continue
            blocks.append((start, end + 1, content[start : end + 1]))

        # Identify synthetic footprints (no pad lines)
        synthetic_blocks = []
        for start, end, block in blocks:
            if "(pad " not in block:
                synthetic_blocks.append((start, end, block))

        if not synthetic_blocks:
            return content, {
                "expanded": 0,
                "failed": 0,
                "skipped": len(blocks),
                "total_footprints": len(blocks),
                "errors": [],
            }

        if dry_run:
            return content, {
                "expanded": 0,
                "failed": 0,
                "skipped": len(blocks) - len(synthetic_blocks),
                "total_footprints": len(blocks),
                "synthetic_found": len(synthetic_blocks),
                "errors": [],
            }

        # Process blocks from bottom to top to preserve offsets
        synthetic_blocks.sort(key=lambda b: b[0], reverse=True)
        new_content = content

        for start, end, block in synthetic_blocks:
            # Extract lib_id — try (lib_id "...") field first,
            # then fall back to (footprint "LIB:FP" ...) KiCad 10 format
            lib_id_match = re.search(r'\(lib_id "([^"]+)"', block)
            if not lib_id_match:
                lib_id_match = re.search(
                    r'\(footprint "([^"]+)"', block
                )
            if not lib_id_match:
                failed += 1
                errors.append(f"No lib_id found in block at offset {start}")
                continue

            lib_id = lib_id_match.group(1)

            # Extract reference for error reporting
            ref_match = re.search(r'\(property "Reference" "([^"]+)"', block)
            ref = ref_match.group(1) if ref_match else "unknown"

            # Extract preserved placement fields
            at_match = re.search(r'\(at ([\d.\-]+) ([\d.\-]+)(?: ([\d.\-]+))?\)', block)
            layer_match = re.search(r'\(layer "([^"]+)"', block)
            tstamp_match = re.search(r'\(tstamp "([^"]+)"', block)
            uuid_match = re.search(r'\(uuid "([^"]+)"', block)

            # Resolve library path
            try:
                mod_path = resolve_footprint_path(lib_id, pcb_path)
            except (ValueError, FileNotFoundError) as e:
                failed += 1
                errors.append(f"{ref}: cannot resolve '{lib_id}': {e}")
                continue

            # Read library footprint
            try:
                lib_content = mod_path.read_text(encoding="utf-8")
            except Exception as e:
                failed += 1
                errors.append(f"{ref}: cannot read '{mod_path}': {e}")
                continue

            # Strip library-only metadata
            lib_content = _strip_library_metadata(lib_content)

            # Extract pad net assignments from synthetic block (if any)
            pad_nets = {}
            for pm in re.finditer(
                r'\(pad "(\d+)"[^)]*\(net (\d+) "([^"]+)"', block
            ):
                pad_nets[pm.group(1)] = (pm.group(2), pm.group(3))

            # Inject preserved placement data into library content.
            # The .kicad_mod file uses \t indentation — preserve it.
            # Note: library footprints may not have a top-level (at ...) line,
            # so we insert after (layer ...) if no existing (at ...) is found.
            if at_match:
                at_sexpr = f"\t(at {at_match.group(1)} {at_match.group(2)}"
                if at_match.group(3):
                    at_sexpr += f" {at_match.group(3)}"
                at_sexpr += ")"
                existing_at = re.search(r"^\t\(at [^\)]*\)", lib_content, flags=re.MULTILINE)
                if existing_at:
                    lib_content = (
                        lib_content[: existing_at.start()]
                        + at_sexpr
                        + lib_content[existing_at.end() :]
                    )
                else:
                    # Insert after (layer ...) line
                    lib_content = _insert_after_field(
                        lib_content,
                        r'^\t\(layer "[^"]*"\)',
                        "\n" + at_sexpr,
                    )

            # Preserve layer
            if layer_match:
                lib_content = re.sub(
                    r'^\t\(layer "[^"]*"\)',
                    f'\t(layer "{layer_match.group(1)}")',
                    lib_content,
                    count=1,
                    flags=re.MULTILINE,
                )

            # Add tstamp/uuid (KiCad 10 format)
            if tstamp_match:
                lib_content = _insert_after_field(
                    lib_content,
                    r'^\t\(layer "[^"]*"\)',
                    f'\n\t(tstamp "{tstamp_match.group(1)}")',
                )
            elif uuid_match:
                lib_content = _insert_after_field(
                    lib_content,
                    r'^\t\(layer "[^"]*"\)',
                    f'\n\t(uuid "{uuid_match.group(1)}")',
                )

            # Preserve reference and value properties
            ref_prop = re.search(r'\(property "Reference" "([^"]+)"', block)
            val_prop = re.search(r'\(property "Value" "([^"]+)"', block)
            if ref_prop:
                lib_content = re.sub(
                    r'\t\(property "Reference" "[^"]*"',
                    f'\t(property "Reference" "{ref_prop.group(1)}"',
                    lib_content,
                    count=1,
                )
            if val_prop:
                lib_content = re.sub(
                    r'\t\(property "Value" "[^"]*"',
                    f'\t(property "Value" "{val_prop.group(1)}"',
                    lib_content,
                    count=1,
                )

            # Re-inject pad net assignments using balanced-paren matching
            for pad_num, (net_id, net_name) in pad_nets.items():
                pad_start = _find_pad_block(lib_content, pad_num)
                if pad_start is not None:
                    pad_end = PcbRawWriter._find_matching_close(lib_content, pad_start)
                    if pad_end is not None:
                        pad_block = lib_content[pad_start:pad_end + 1]
                        lib_content = (
                            lib_content[:pad_start]
                            + _inject_pad_net(pad_block, net_id, net_name)
                            + lib_content[pad_end + 1:]
                        )

            # Preserve original indentation
            line_start = content.rfind("\n", 0, start) + 1
            fp_open = content.index("(", line_start)
            indent = content[line_start:fp_open]
            indented_lib = indent + lib_content.replace("\n", "\n" + indent)

            new_content = new_content[:start] + indented_lib + new_content[end:]
            expanded += 1

        return new_content, {
            "expanded": expanded,
            "failed": failed,
            "skipped": len(blocks) - len(synthetic_blocks),
            "total_footprints": len(blocks),
            "errors": errors,
        }


def _strip_library_metadata(sexp: str) -> str:
    """Remove library-only fields from a .kicad_mod file for PCB embedding."""
    for pattern in [
        r"^\t?\(version [^\)]*\)\s*\n",
        r'^\t?\(generator "[^"]*"\)\s*\n',
        r'^\t?\(generator_version "[^"]*"\)\s*\n',
        r'^\t?\(compatibility "[^"]*"\s*\([^)]*\)\)\s*\n',
        r'^\t\(descr ".*"\)\s*\n',
        r'^\t\(tags ".*"\)\s*\n',
    ]:
        sexp = re.sub(pattern, "", sexp, flags=re.MULTILINE)
    return sexp


def _insert_after_field(sexp: str, field_pattern: str, insertion: str) -> str:
    """Insert text after the line matching field_pattern."""
    match = re.search(field_pattern, sexp, re.MULTILINE)
    if match:
        end = match.end()
        sexp = sexp[:end] + insertion + sexp[end:]
    return sexp


def _find_pad_block(content: str, pad_num: str) -> int | None:
    """Find the start offset of a pad block by pad number."""
    m = re.search(r'\(pad "' + re.escape(pad_num) + r'"', content)
    return m.start() if m else None


def _inject_pad_net(pad_sexpr: str, net_id: str, net_name: str) -> str:
    """Inject or replace net assignment in a pad S-expression.

    The pad_sexpr is the full balanced-paren pad block including
    the opening (pad ... and closing ).
    """
    if "(net " in pad_sexpr:
        return re.sub(
            r'\(net \d+ "[^"]*"\)',
            f'(net {net_id} "{net_name}")',
            pad_sexpr,
            count=1,
        )
    else:
        # Insert net before the final closing paren
        return pad_sexpr.rstrip().rstrip(")") + f' (net {net_id} "{net_name}")\n\t)'
